name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5

      - name: Install and build
        run: |
          yarn install
          yarn run build


      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with: 
          path: "./dist"

      - name: Publish deployed code 
        uses: actions/upload-artifact@v2
        with:
          name: published
          path: dist